basic_settings:
  site_title: Abschlussarbeiten @cnoss
  site_tagline: Professur für Kommunikationsdesign in der Medieninformatik
  favicon_image: /assets/img/favicon.ico
  description: Ein bisschen Struktur und Prozess für Projekt- und Abschlussarbeiten unter meiner Betreuung.
